### PR TITLE
Rename package for better search

### PR DESCRIPTION
**Pull request by renatoselenica**
Sorry a very small misunderstanding and a bad explanation from my part. The previous pull request just fixed the link to the repo and added the description. 

This one fixes the name so the search will work optimally for the package to be easily found on the marketplace

P.s. You will need to do a `npm install` because I did not include the package-json.lock because since I am on linux it changes some dependencies and that might affect users.

### CODE REVIEW

**Comment by stolinski** [comment]
Thanks!

**Comment by stolinski** [comment]
On second thought. I'm rolling this one back. I don't want to have to delete the current listing in favor of a new one causing a fragmented audience.

**Comment by renatoselenica** [comment]
Does it have to create a new listing for this change. Isn't it just an update to the existing one? Technically the name of the actual plugin does not change.

**Comment by stolinski** [comment]
I'm pretty sure. I just published it with the name change and that triggered a new package rather than an update. There might be a vsce command that I'm not aware of that will do it, but I'd have to investigate.

**Comment by renatoselenica** [comment]
I think the new package happens because a name change would require also a url change for the plugin. I see why that would be hard to update. So in this scenario keeping the old name seems more opportune.

**Pull request merged**
